# Оценка эффекта воздействия в выбранной модели

В качестве эффекта воздействия рассматривается включение коммунальных услуг в стоимость аренды квартиры

`utilities_included` берем как treatment-переменную

$
utilities\_included =
\begin{cases}
1, & \text{если коммунальные услуги включены в стоимость аренды} \\
0, & \text{иначе}
\end{cases}
$

$
H_1:
\beta_{utilities\_included} > 0
$

то есть включение коммунальных услуг повышает стоимость аренды квартиры

In [1]:
#берем модель 6 из задания 3

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
df = pd.read_excel("data.xlsx")
base_vars = [
    'ln_total_meters',
    'rooms_count',
    'center_distance',
    'metro_time_min'
]

building_vars = [
    'relative_floor',
    'is_apartment'
]

rent_condition_vars = [
    'no_commission',
    'has_deposit',
    'utilities_included',
    'kids_allowed',
    'pets_allowed'
]

amenity_vars = [
    'has_furniture',
    'has_washing_machine',
    'has_dryer',
    'has_fridge',
    'has_tv',
    'has_conditioner',
    'has_dishwasher',
    'has_microwave',
    'has_boiler'
]

repair_vars = [
    'repair_designer',
    'repair_euro'
]

base_vars = [x for x in base_vars if x in df.columns]
building_vars = [x for x in building_vars if x in df.columns]
rent_condition_vars = [x for x in rent_condition_vars if x in df.columns]
amenity_vars = [x for x in amenity_vars if x in df.columns]
repair_vars = [x for x in repair_vars if x in df.columns]
model_cols = ['price', 'ln_price'] + base_vars + building_vars + rent_condition_vars + amenity_vars + repair_vars

df_model = df[model_cols].replace([np.inf, -np.inf], np.nan).dropna().copy()
df_model['amenities_count'] = df_model[amenity_vars].sum(axis=1)

df_model.shape
formula_m6 = '''
ln_price ~ ln_total_meters
         + rooms_count
         + center_distance
         + relative_floor
         + is_apartment
         + utilities_included
         + repair_euro
         + amenities_count
'''

model_6 = smf.ols(formula_m6, data=df_model).fit()

In [2]:
#считаем эффект
beta = model_6.params['utilities_included']
effect = np.exp(beta) - 1
print("Coefficient:", beta)
print("Treatment effect:", effect)
print("P-value:", model_6.pvalues['utilities_included'])

Coefficient: 0.06465016883593688
Treatment effect: 0.06678576419328208
P-value: 0.09813056230613715

Получаем, эффект воздействия составляет: $e^{0.0647} - 1 \approx 0.0668$
 -квартиры, в стоимость аренды которых включены коммунальные услуги, в среднем стоят примерно на 6.7% дороже при прочих равных условиях.

Полученный эффект статистически значим на 10%-м уровне: $p\text{-value} = 0.098$

Результат в целом ожидаем: включение коммунальных услуг делает условия аренды более удобными для арендаторов, что позволяет арендодателям устанавливать более высокую цену

## Квантильная регрессия

В качестве дополнительной модели строим квантильную регрессию. Ее применение оправдано: рынок аренды жилья является неоднородным, и факторы, влияющие на дешёвые квартиры, могут иначе воздействовать на более дорогие объекты

оценим модели для 25-го квантиля распределения, 50-го, и 75-го

$
H_1:\text{влияние факторов на стоимость аренды различается между ценовыми сегментами рынка}
$

In [3]:
quantiles = [0.25, 0.5, 0.75]
qr_results = {}
for q in quantiles:
    model = smf.quantreg(formula_m6, df_model).fit(q=q)

    qr_results[q] = model

    print("\n" + "="*80)
    print(f"Quantile regression, q = {q}")
    print(model.summary())

================================================================================
Quantile regression, q = 0.25
                         QuantReg Regression Results
==============================================================================
Dep. Variable:               ln_price   Pseudo R-squared:               0.2909
Model:                       QuantReg   Bandwidth:                      0.1876
Method:                 Least Squares   Sparsity:                        1.044
Date:                Thu, 07 May 2026   No. Observations:                  987
Time:                        09:36:35   Df Residuals:                      978
                                        Df Model:                            8
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              9.8987      0.163     60.878      0.000       9.580      10.218
ln_total_meters        0.2927      0.047      6.242      0.000       0.201       0.385
rooms_count            0.2086      0.029      7.286      0.000       0.152       0.265
center_distance       -0.0074      0.002     -3.104      0.002      -0.012      -0.003
relative_floor        -0.0041      0.051     -0.081      0.936      -0.104       0.096
is_apartment           0.1850      0.049      3.797      0.000       0.089       0.281
utilities_included     0.0581      0.034      1.712      0.087      -0.009       0.125
repair_euro           -0.0272      0.033     -0.836      0.403      -0.091       0.037
amenities_count       -0.0343      0.008     -4.470      0.000      -0.049      -0.019
======================================================================================

================================================================================
Quantile regression, q = 0.5
                         QuantReg Regression Results
==============================================================================
Dep. Variable:               ln_price   Pseudo R-squared:               0.3406
Model:                       QuantReg   Bandwidth:                      0.2094
Method:                 Least Squares   Sparsity:                        1.043
Date:                Thu, 07 May 2026   No. Observations:                  987
Time:                        09:36:35   Df Residuals:                      978
                                        Df Model:                            8
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             10.0000      0.187     53.358      0.000       9.632      10.368
ln_total_meters        0.3320      0.053      6.275      0.000       0.228       0.436
rooms_count            0.2274      0.031      7.286      0.000       0.166       0.289
center_distance       -0.0082      0.003     -3.022      0.003      -0.014      -0.003
relative_floor        -0.0448      0.060     -0.750      0.453      -0.162       0.072
is_apartment           0.1626      0.056      2.912      0.004       0.053       0.272
utilities_included     0.0694      0.039      1.788      0.074      -0.007       0.145
repair_euro           -0.0425      0.037     -1.151      0.250      -0.115       0.030
amenities_count       -0.0360      0.009     -3.934      0.000      -0.054      -0.018
======================================================================================

================================================================================
Quantile regression, q = 0.75
                         QuantReg Regression Results
==============================================================================
Dep. Variable:               ln_price   Pseudo R-squared:               0.3639
Model:                       QuantReg   Bandwidth:                      0.1871
Method:                 Least Squares   Sparsity:                        1.555
Date:                Thu, 07 May 2026   No. Observations:                  987
Time:                        09:36:35   Df Residuals:                      978
                                        Df Model:                            8
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             10.2116      0.259     39.457      0.000       9.704      10.720
ln_total_meters        0.4338      0.073      5.970      0.000       0.291       0.576
rooms_count            0.2039      0.041      4.997      0.000       0.124       0.284
center_distance       -0.0186      0.003     -5.361      0.000      -0.025      -0.012
relative_floor        -0.1689      0.080     -2.115      0.035      -0.326      -0.012
is_apartment           0.2099      0.074      2.841      0.005       0.065       0.355
utilities_included     0.0936      0.049      1.900      0.058      -0.003       0.190
repair_euro           -0.0872      0.047     -1.853      0.064      -0.180       0.005
amenities_count       -0.0410      0.012     -3.294      0.001      -0.065      -0.017
======================================================================================

In [4]:
qr_table = pd.DataFrame({
    q: qr_results[q].params
    for q in quantiles
})

qr_table

                        0.25       0.50       0.75
Intercept           9.898681  10.000039  10.211638
ln_total_meters     0.292665   0.331981   0.433816
rooms_count         0.208583   0.227429   0.203929
center_distance    -0.007423  -0.008237  -0.018640
relative_floor     -0.004104  -0.044837  -0.168854
is_apartment        0.185040   0.162650   0.209935
utilities_included  0.058071   0.069375   0.093569
repair_euro        -0.027180  -0.042544  -0.087241
amenities_count    -0.034285  -0.035963  -0.041022

In [5]:
qr_pvalues = pd.DataFrame({
    q: qr_results[q].pvalues
    for q in quantiles
})

qr_pvalues

                            0.25           0.50           0.75
Intercept           0.000000e+00  6.863517e-292  1.786044e-204
ln_total_meters     6.435484e-10   5.251008e-10   3.310029e-09
rooms_count         6.576571e-13   6.547338e-13   6.898070e-07
center_distance     1.964788e-03   2.574357e-03   1.032997e-07
relative_floor      9.356215e-01   4.534856e-01   3.465725e-02
is_apartment        1.554360e-04   3.674651e-03   4.586605e-03
utilities_included  8.727142e-02   7.400760e-02   5.772475e-02
repair_euro         4.034670e-01   2.501030e-01   6.420706e-02
amenities_count     8.721386e-06   8.956907e-05   1.023559e-03

Итак, влияние факторов действительно различается для разных ценовых сегментов!

### Площадь квартиры

Коэффициент при переменной `ln_total_meters` увеличивается при переходе к более дорогим квартирам:

| Квантиль | Коэффициент |
|---|---|
| 0.25 | 0.293 |
| 0.50 | 0.332 |
| 0.75 | 0.434 |

Все коэффициенты статистически значимы.

То есть, площадь особенно важна для дорогих квартир

---

### Расстояние до центра

Влияние расстояния до центра также усиливается в верхнем сегменте рынка:

| Квантиль | Коэффициент |
|---|---|
| 0.25 | -0.007 |
| 0.50 | -0.008 |
| 0.75 | -0.019 |

Следовательно, удалённость от центра сильнее снижает стоимость дорогих квартир

---

### Относительный этаж

Для дешёвых и средних квартир переменная `relative_floor` статистически незначима.

Однако для верхнего квантиля коэффициент становится отрицательным и значимым:

$$
\beta = -0.169
$$

Это может означать, что для дорогих квартир расположение на менее удобных этажах сильнее влияет на цену.

---

### Апартаменты

Переменная `is_apartment` остаётся положительной и статистически значимой во всех квантилях

---

### Включённые коммунальные услуги

Коэффициент при `utilities_included` положителен во всех моделях:

| Квантиль | Коэффициент |
|---|---|
| 0.25 | 0.058 |
| 0.50 | 0.069 |
| 0.75 | 0.094 |

Эффект усиливается в верхнем сегменте рынка, включённые коммунальные услуги особенно ценятся в дорогих квартирах.

---



Таким образом, квантильная регрессия подтверждает неоднородность рынка аренды жилья.